# Generated by Django 4.2 on 2023-05-08 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('glas_cutr', '0003_alter_homecap_cover_image_alter_logo_logo_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='button_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
