# Generated by Django 4.2 on 2023-05-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glas_cutr', '0004_aboutus_button_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='button_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='homecap',
            name='button_url',
            field=models.CharField(max_length=200),
        ),
    ]
