# Generated by Django 4.2 on 2023-05-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glas_cutr', '0008_team_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='description_bold',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='management',
            name='description_prev',
            field=models.CharField(max_length=50),
        ),
    ]
