# Generated by Django 4.2 on 2023-05-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glas_cutr', '0011_subservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelist',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
