# Generated by Django 4.2 on 2023-05-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glas_cutr', '0013_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='height',
            field=models.IntegerField(default=20),
        ),
    ]
