# Generated by Django 4.2 on 2023-05-08 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('glas_cutr', '0014_tool_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
